version: '3'
services:
  db:
    image: mysql:5.7
    container_name: rails_on_docker_mysql
    environment:
      MYSQL_DATABASE: rails_on_docker_dev
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      TZ: 'Asia/Tokyo'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - rails_on_docker_network
    ports:
      - 3306:3306
  web:
    build: .
    container_name: rails_on_docker
    environment:
      DB_HOST: db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 9000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
    networks:
      - rails_on_docker_network
    ports:
      - "9000:9000"
    depends_on:
      - db
networks:
  rails_on_docker_network:
    external: true
